const slidesData = [
  {
    mainText: "VINTAGE VENEER - VV",
    subText: "Peacefull",
    collection: "Collection/Compact Laminates/Standard Compacts/",
    category: "Solids",
    designNumber: "123",
    designName: "Terracotta",
    finishName: "Suede",
    finishCode: "123",  
    Thickness: "3mm to 25mm",
    DimensionsMm: "1220x2440 | 1525x3660 | 1830x3660",
    DimensionsFt: "4'x8' | 5'x12' | 6'x12'",
    PfnPF: "Peacefull",
    buttonText: "Enquire now",
    buttonUrl: "/",
  },
  {
    mainText: "VINTAGE VENEER - VV1",
    subText: "Peacefull1",
    collection: "Collection/Compact Laminates/Standard Compacts/1",
    category: "Solids1",
    designNumber: "1231",
    designName: "Terracotta1",
    finishName: "Suede1",
    finishCode: "1231",
    Thickness: "3mm to 25mm",
    DimensionsMm: "1220x2440 | 1525x3660 | 1830x3660",
    DimensionsFt: "4'x8' | 5'x12' | 6'x12'",
    PfnPF: "Peacefull",
    buttonText: "Enquire now",
    buttonUrl: "/",
  },
  {
    mainText: "VINTAGE VENEER - VV2",
    subText: "Peacefull2",
    collection: "Collection/Compact Laminates/Standard Compacts/2",
    category: "Solids2",
    designNumber: "1232",
    designName: "Terracotta2",
    finishName: "Suede2",
    finishCode: "1232",
    Thickness: "3mm to 25mm",
    DimensionsMm: "1220x2440 | 1525x3660 | 1830x3660",
    DimensionsFt: "4'x8' | 5'x12' | 6'x12'",
    PfnPF: "Peacefull",
    buttonText: "Enquire now",
    buttonUrl: "/",
  },
];

export default slidesData;
